/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ClickedOption, Option, SelectedOptions } from "./components/ui-chips/ui-chips-type";
export namespace Components {
    interface UiChips {
        "error": string;
        "hint": string;
        "label": string;
        "name": string;
        "optionalLabel": string;
        "options": Option[];
        /**
          * public 'select' function.
          * @param index the array item index
         */
        "select": (index: number) => Promise<void>;
        "selectable": boolean;
        "type": string;
    }
}
declare global {
    interface HTMLUiChipsElement extends Components.UiChips, HTMLStencilElement {
    }
    var HTMLUiChipsElement: {
        prototype: HTMLUiChipsElement;
        new (): HTMLUiChipsElement;
    };
    interface HTMLElementTagNameMap {
        "ui-chips": HTMLUiChipsElement;
    }
}
declare namespace LocalJSX {
    interface UiChips {
        "error"?: string;
        "hint"?: string;
        "label"?: string;
        "name"?: string;
        "onUiChipsClick"?: (event: CustomEvent<ClickedOption>) => void;
        "onUiChipsSelect"?: (event: CustomEvent<ClickedOption | SelectedOptions>) => void;
        "optionalLabel"?: string;
        "options"?: Option[];
        "selectable"?: boolean;
        "type"?: string;
    }
    interface IntrinsicElements {
        "ui-chips": UiChips;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-chips": LocalJSX.UiChips & JSXBase.HTMLAttributes<HTMLUiChipsElement>;
        }
    }
}
